### ISSUE TITLE
频繁切换会有问题，会超时anr

### ISSUE THREAD

**Issue by jieray** [AnyLifeZLB/ScrollTextView#29]
at java.lang.Thread.parkFor$(Thread.java:1220)
  - locked <0x0d1ebfb8> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:299)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:844)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1173)
  at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:181)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:257)
  at android.view.SurfaceView.updateWindow(SurfaceView.java:564)
  at android.view.SurfaceView.setVisibility(SurfaceView.java:287)
  at com.huazhu.ehotel.view.ScrollTextView.onVisibilityChanged(ScrollTextView.java:483)
  at android.view.View.dispatchVisibilityChanged(View.java:9579)
  at android.view.View.setFlags(View.java:10640)
  at android.view.View.setVisibility(View.java:7425)
  at android.view.SurfaceView.setVisibility(SurfaceView.java:274)
  at com.huazhu.ehotel.ui.movie.TvPlayDetailByIdActivity.onPause(TvPlayDetailByIdActivity.java:990)
  at android.app.Activity.performPause(Activity.java:6358)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
  at android.app.ActivityThread.-wrap13(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5431)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)

**Comment by AnyLifeZLB** [comment]
频繁切换滚动的文字吗？还是？我来看看能否复现修复问题

有些CUSTOM电视盒子可能软硬件设备 有问题，可以尝试在平板上对比一下

**Comment by lylelqc** [comment]
随着界面显隐，频繁创建销毁会导致surfaceview重影，这个由什么解决方式吗？设置了setZorderOnTop(true)

**Comment by AnyLifeZLB** [comment]
@lylelqc 什么设备会出现这个问题，手机也会吗？

**Comment by dacaoyuan** [comment]
我的也是错误日志如下：
/SurfaceHolder: Exception locking surface
    java.lang.IllegalArgumentException
        at android.view.Surface.nativeLockCanvas(Native Method)
        at android.view.Surface.lockCanvas(Surface.java:310)
        at android.view.SurfaceView$4.internalLockCanvas(SurfaceView.java:990)
        at android.view.SurfaceView$4.lockCanvas(SurfaceView.java:958)
        at anylife.scrolltextview.ScrollTextView.draw(ScrollTextView.java:475)
        at anylife.scrolltextview.ScrollTextView.access$600(ScrollTextView.java:38)
        at anylife.scrolltextview.ScrollTextView$ScrollTextThread.run(ScrollTextView.java:532)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2022-07-23 12:18:30.614 1305-12347/system_process W/WindowManager: Failed looking up window

**Comment by vince-styling** [comment]
有点疑惑，为什么要用 SurfaceView，不觉得有点重量级吗，据我了解，SurfaceView 不支持别的 view 盖在它上面，哪怕是用 TextureView 也好啊

**Comment by AnyLifeZLB** [comment]
今天使用低端机发现问题比较严重，这周会优化一版本
